'use strict';

/**
 * Lookup over the choir-asset index — "what music do we hold for this service,
 * and for this hymn?"
 *
 * The index is generated by scripts/choir-index-build.js and addressed
 * liturgically; the packet folders it derives from are addressed by provenance.
 * See docs/choir-asset-addressing-design.md.
 *
 * Metadata and locations; the bytes are served by routes/api-choir-asset.js.
 *
 * The choir director (Connie Russell) granted reuse of these documents on
 * 2026-10-01, so `url` is populated for anything present on disk. That grant
 * covers the parish's own compiled material; several sheets carry third-party
 * settings (OBIKHOD, Znamenny, Byzantine arrangements) whose rights sit with
 * their publishers, so this is the parish using its own books rather than a
 * public redistribution point. See docs/choir-asset-addressing-design.md §5.
 *
 * `available` reports whether the file is on this machine — in production it is
 * false, because the per-packet `pdf` directories are gitignored and never
 * deploy. Permission did not change that; it is a storage question (§6).
 */

const fs   = require('fs');
const path = require('path');

const ROOT       = path.resolve(__dirname, '..', '..');
const INDEX_PATH = path.join(ROOT, 'docs', 'choir-packets', 'index.json');

let cache = null;   // { mtimeMs, index }

/** Reload when the file changes, so a rebuilt index is picked up without a restart. */
function loadIndex() {
  let stat;
  try { stat = fs.statSync(INDEX_PATH); }
  catch { return { bindings: [], assets: {} }; }          // no index yet — not an error

  if (cache && cache.mtimeMs === stat.mtimeMs) return cache.index;
  try {
    const index = JSON.parse(fs.readFileSync(INDEX_PATH, 'utf8'));
    cache = { mtimeMs: stat.mtimeMs, index };
    return index;
  } catch {
    return cache ? cache.index : { bindings: [], assets: {} };
  }
}

/** The director's section names → ours, as emitted in ServiceBlock.section. */
const SECTION_ALIASES = {
  'Lord I Call': 'Lord, I Have Cried',
  'Aposticha':   'Aposticha',
  'Troparion':   'Troparia',
  'Litya':       'Litya',
  'Theotokion':  null,     // appears inside several sections; never a section itself
  'Prokeimenon': 'Evening Prokeimenon',
};

/**
 * Archaic → modern, so a `tt` render can be compared with the director's `yy`
 * sources. Deliberately shallow: this normalizes for COMPARISON only, and a
 * comparison that fails simply declines to bind.
 */
const ARCHAIC = {
  thou: 'you', thee: 'you', thy: 'your', thine: 'your', ye: 'you',
  hast: 'have', hath: 'has', art: 'are', wast: 'were', shalt: 'will',
  didst: 'did', dost: 'do', doth: 'does', canst: 'can', wilt: 'will',
  unto: 'to', upon: 'on',
};

function normalizeIncipit(s) {
  return String(s || '')
    .toLowerCase()
    .replace(/\*/g, ' ')                       // our stichera carry * phrase marks
    .replace(/[^a-z0-9\s]/g, ' ')
    .split(/\s+/)
    .filter(Boolean)
    // A crude stem, applied identically to both sides. It only has to be
    // CONSISTENT, not linguistically right: "endureth" and "endures" must land
    // on the same token, which an eth-only strip failed to do. The real signal
    // lives in the explicit ARCHAIC map above; precision comes from the section
    // and tone gates, not from here.
    .map((w) => ARCHAIC[w] || w
      .replace(/(?:eth|est)$/, '')
      .replace(/(?<![s])s$/, '')
      .replace(/e$/, ''))
    .filter(Boolean);
}

/**
 * Does a rendered block's text begin with the director's incipit?
 *
 * Prefix containment, not similarity. Precision matters far more than recall
 * here: a wrong attachment points a singer at the wrong sheet, while a missing
 * one just leaves the sheet in the service-level list. Measured on 2026-07-01,
 * only 2 of 5 incipits match — the rest are the same hymn in a different
 * translation ("As you received grace from" vs "Having received grace freely
 * from Christ God"), which no amount of fuzzing should be allowed to bind.
 *
 * The director's incipit is truncated at an arbitrary point — "Boundless is the
 * grace that" against our "Boundless is the grace of the saints" — so only its
 * LEADING words are reliable. Four is enough to identify a hymn inside a
 * (section, tone) bucket, and section + tone carry most of the precision burden.
 *
 * @returns {number} 1 for a leading-word match, 0 for no match.
 */
const PREFIX_WORDS = 4;

function incipitMatches(blockText, incipit) {
  const want = normalizeIncipit(incipit);
  const got  = normalizeIncipit(blockText);
  if (want.length < 3 || got.length < 3) return 0;
  const n = Math.min(PREFIX_WORDS, want.length, got.length);
  if (n < 3) return 0;
  for (let i = 0; i < n; i++) if (want[i] !== got[i]) return 0;
  return 1;
}

/**
 * Services filed under the civil evening whose content is the NEXT day's entry.
 * Mirrors scripts/choir-mail-parse.js, derived the same way: the catalog entries
 * whose isServed() reads `vespersEntry` rather than `cur`. `burialVespers` is
 * deliberately absent — its shift has not been verified.
 */
const DATE_SHIFTED = new Set(['greatVespers', 'dailyVespers', 'allNightVigil']);

/**
 * A binding's `scope` (set at index-build time from the folder it came from)
 * limits which services may offer it. Without this, the 97 per-hymn Vespers
 * sheets were offered for Matins and Liturgy too, because they share a date.
 */
const SCOPE_SERVICES = {
  vespers: new Set(['greatVespers', 'dailyVespers', 'allNightVigil', 'burialVespers',
                    'kneelingVespers', 'vesperalLiturgy', 'presanctified']),
  liturgy: new Set(['liturgy', 'vesperalLiturgy', 'presanctified']),
  matins:  new Set(['matins', 'allNightVigil', 'bridegroomMatins']),
};

/** Unscoped bindings are offered everywhere; a scoped one only where it belongs. */
const inScope = (binding, serviceKey) => {
  if (!binding.scope) return true;
  const allowed = SCOPE_SERVICES[binding.scope];
  return allowed ? allowed.has(serviceKey) : true;
};

function contentDateFor(date, serviceKey) {
  if (!DATE_SHIFTED.has(serviceKey)) return date;
  const d = new Date(`${date}T12:00:00Z`);
  d.setUTCDate(d.getUTCDate() + 1);
  return d.toISOString().slice(0, 10);
}

const assetOf = (index, id) => index.assets?.[id] || null;

function describe(index, binding) {
  const a = assetOf(index, binding.asset);
  const rel = a?.path || null;
  let available = false;
  if (rel) {
    try { available = fs.existsSync(path.join(ROOT, 'docs', 'choir-packets', rel))
                   || fs.existsSync(path.join(ROOT, rel)); } catch { available = false; }
  }
  return {
    asset: binding.asset,
    filename: a?.filename || null,
    pages: a?.pages ?? null,
    path: rel,
    available,
    // Fetchable only where the file is actually on disk. Reuse was granted by
    // the director 2026-10-01 (design §5); the scans are gitignored, so in
    // production `available` is false and this is null.
    url: available ? `/api/choir-asset?id=${binding.asset}` : null,
    packet: binding.packet,
  };
}

/**
 * Everything we hold that bears on one service.
 *
 * @param {string} date        the civil date the service is sung (apiDate)
 * @param {string} serviceKey  catalog key, e.g. 'greatVespers'
 * @param {object} [opts]
 * @param {string} [opts.contentDate] the liturgical day, when it differs
 * @param {number} [opts.tone]
 */
function musicForService(date, serviceKey, opts = {}) {
  const index = loadIndex();
  const bindings = index.bindings || [];
  const contentDate = opts.contentDate || date;

  const booklet = bindings
    .filter((b) => b.kind === 'service' && b.date === date && b.service === serviceKey)
    .filter((b) => inScope(b, serviceKey))
    .map((b) => ({ role: 'booklet', ...describe(index, b) }));

  const standing = bindings
    .filter((b) => b.kind === 'standing'
                && (!b.service || b.service === serviceKey)
                && (!b.from || b.from <= date)
                && inScope(b, serviceKey))
    .map((b) => ({ role: b.role || 'standing', title: b.title || null,
                   unless: b.unless || null, ...describe(index, b) }));

  const tone = opts.tone == null ? [] : bindings
    .filter((b) => b.kind === 'tone' && b.tone === opts.tone && inScope(b, serviceKey))
    .map((b) => ({ role: b.role || 'tone', tone: b.tone, ...describe(index, b) }));

  const day = bindings
    .filter((b) => b.kind === 'day' && b.contentDate === contentDate && inScope(b, serviceKey))
    .map((b) => ({ role: 'day-sheet', title: b.title || null, ...describe(index, b) }));

  // Per-hymn sheets for this service: a Vespers section's sheet carries the
  // eve in apiDate, everything else is keyed by the liturgical day.
  const blocks = bindings
    .filter((b) => b.kind === 'block'
                && inScope(b, serviceKey)
                && (b.apiDate === date || (b.apiDate == null && b.contentDate === contentDate)))
    .map((b) => ({
      role: 'hymn', section: b.section, ourSection: SECTION_ALIASES[b.section] || null,
      position: b.position, tone: b.tone, melody: b.melody,
      commemoration: b.commemoration, incipit: b.incipit,
      ...describe(index, b),
    }));

  return { booklet, standing, tone, day, blocks };
}

/**
 * Attach per-hymn sheets to the blocks they belong to, in place of guessing.
 *
 * A sheet is attached only when section AND tone agree and the incipit is a
 * clean prefix of the rendered text. A tone disagreement refuses the binding
 * outright rather than warning — the tone is the one field that matched on every
 * pair we measured, so a mismatch means we have the wrong hymn.
 *
 * Whatever does not attach stays in `music.blocks`, visible rather than lost.
 *
 * @returns {{attached: number, unattached: Array}}
 */
function attachToBlocks(serviceBlocks, hymnSheets) {
  const remaining = [...(hymnSheets || [])];
  let attached = 0;

  for (const block of serviceBlocks || []) {
    if (!block || !block.text) continue;
    const i = remaining.findIndex((h) =>
      h.ourSection && h.ourSection === block.section
      && h.tone != null && block.tone != null && h.tone === block.tone
      && incipitMatches(block.text, h.incipit));
    if (i === -1) continue;
    const [hit] = remaining.splice(i, 1);
    block.music = [{
      asset: hit.asset, filename: hit.filename, pages: hit.pages,
      path: hit.path, available: hit.available, melody: hit.melody,
      position: hit.position, match: 'incipit-prefix',
    }];
    attached++;
  }
  return { attached, unattached: remaining };
}

// ── search ────────────────────────────────────────────────────────────────

/** A one-line human label for a binding, used in search results. */
function labelFor(b) {
  switch (b.kind) {
    case 'service':
      return `${b.service} booklet — ${b.date}`;
    case 'block':
      return [b.section, b.position && `@${b.position}`, b.commemoration && `— ${b.commemoration}`]
        .filter(Boolean).join(' ');
    case 'tone':
      return `Tone ${b.tone}${b.role === 'intro-packet' ? ' intro packet' : ' setting'}`;
    case 'day':
      return b.title || `day sheet — ${b.contentDate}`;
    case 'standing':
      return b.title || 'standing item';
    default:
      return b.kind;
  }
}

/**
 * Free-text search across the choir assets.
 *
 * Fields are weighted by how specific they are: a commemoration or a title names
 * the piece, a melody or incipit narrows it, a section or filename barely
 * distinguishes anything. "tone 8" is read as a tone filter rather than as text,
 * since that is what a chorister means by it.
 *
 * @returns {Array} highest score first
 */
function searchMusic(query, opts = {}) {
  const limit = opts.limit || 25;
  const raw = String(query || '').trim();
  if (raw.length < 2) return [];

  const index = loadIndex();
  const q = raw.toLowerCase();

  // "tone 8" / "tone8" — a filter, not a substring to find.
  const toneAsked = raw.match(/\btone\s*(\d)\b/i);
  const wantTone = toneAsked ? Number(toneAsked[1]) : null;
  const text = q.replace(/\btone\s*\d\b/i, '').trim();

  const hit = (field, weight) =>
    field && String(field).toLowerCase().includes(text) ? weight : 0;

  const out = [];
  for (const b of index.bindings || []) {
    if (b.kind === 'superseded') continue;
    if (wantTone != null && b.tone !== wantTone) continue;

    const a = assetOf(index, b.asset);
    let score = 0;
    if (text) {
      score += hit(b.commemoration, 10);
      score += hit(b.title, 10);
      score += hit(b.incipit, 6);
      score += hit(b.melody, 5);
      score += hit(b.service, 3);
      score += hit(b.section, 2);
      score += hit(a?.filename, 1);
      if (score === 0) continue;
    } else if (wantTone == null) {
      continue;
    } else {
      score = 1;                                  // tone-only query: all matches equal
    }

    out.push({
      kind: b.kind, label: labelFor(b), score,
      date: b.date || b.apiDate || null,
      contentDate: b.contentDate || null,
      service: b.service || null,
      section: b.section || null, position: b.position || null,
      tone: b.tone ?? null, melody: b.melody || null,
      commemoration: b.commemoration || null, incipit: b.incipit || null,
      scope: b.scope || null,
      ...describe(index, b),
    });
  }

  // Unbound assets must be findable too. "Lord Have Mercy (Byzantine)" is real
  // material the choir sings; it simply has no date or service yet, and leaving
  // it out of search would hide the backlog instead of surfacing it.
  if (text && wantTone == null) {
    for (const u of index.unbound || []) {
      const score = hit(u.filename, 4);
      if (!score) continue;
      out.push({
        kind: 'unbound', label: String(u.filename || '').replace(/\.pdf$/i, ''),
        score, date: null, contentDate: null, service: null,
        section: null, position: null, tone: null, melody: null,
        commemoration: null, incipit: null, scope: null,
        note: 'not yet bound to a service or date',
        ...describe(index, u),
      });
    }
  }

  out.sort((x, y) => y.score - x.score
    || String(x.date || '').localeCompare(String(y.date || ''))
    || String(x.label).localeCompare(String(y.label)));
  return out.slice(0, limit);
}

module.exports = {
  loadIndex, musicForService, attachToBlocks, contentDateFor, searchMusic,
  incipitMatches, normalizeIncipit, labelFor, SECTION_ALIASES, DATE_SHIFTED,
};
